// <auto-generated />
namespace Macservice.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Add_colum_Demo_address : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_colum_Demo_address));
        
        string IMigrationMetadata.Id
        {
            get { return "202006080824209_Add_colum_Demo_address"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
